### ISSUE TITLE
US3: Like a tweet

### ISSUE THREAD

**Issue by Olihockey17** [samiha-rahman/SOEN341#3]
As a user, I want to be able to like a tweet.

Tasks

- [ ] 1. Like button on an existing tweet 
- [ ] 2. Pop up after liking a tweet that shows that a tweet has been liked  
- [ ] 3. Capacity to unlike a tweet by pressing the same button

**Comment by VictorTudoran** [comment]
I changed the numbering of tasks since the "#" symbol would reference previous issues and commits.

**Comment by davidchen2171** [comment]
Duplicated user story
