### ISSUE TITLE
Users can upload a profile picture

### ISSUE THREAD

**Issue by ThierryRomain** [samiha-rahman/SOEN341#92]
Users must be able to upload a profile picture and see other user's profile pictures beside their woofs. 

Tasks to be tracked: 
- [x] Create a user-profile page where the user can upload the profile picture
- [x] Display the picture on the woofs

------------------------------
**ACCEPTANCE TEST**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Login as a user and go to profile's setting page to upload profile pic | Profile picture should appear  | PASS
2 | Go to explore page | Posts should have the user's profile picture on the left | PASS
3 | Go to Liked, Following page | Posts should have the user's profile picture on the left | PASS

**Comment by samiha-rahman** [comment]
Tasks completed in commit 01b584513bf10fbbc323989d80b6c7fcf740c25a
Acceptance testing remains to be completed before closing this feature.

**Comment by davidchen2171** [comment]
Acceptance test done
