### ISSUE TITLE
Add a counter to keep track of how many likes a post has

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/SOEN341#94]
Related to epic #67; an enhancement to the feature suggested by TA

------------------------------
**ACCEPTANCE TEST**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Go to explore page | The number of likes should not appear on each posts, cannot like | PASSED
2 | Login and go to explore page | The number of likes should appear on each posts, liking the post should increment the like value | PASSED
2 | Login and go to explore page | The number of likes should appear on each posts, unliking the post should decrement the like value | PASSED

**Comment by davidchen2171** [comment]
Acceptance test done
