### ISSUE TITLE
Regression testing to be done upon completion of #75

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/SOEN341#96]
Please conduct a thorough revisit of all features after the UI has been completed to ensure that all functionality remains consistent. I suggest repeating each acceptance test a second time. 

User Story |  Passed/Failed
--- | --- 
#15 | PASS
#20 | PASS
#24 | PASS
#28 | PASS
#32 | PASS
#44 | PASS
#47 | PASS
#60 | PASS
#64 | PASS
#68 | PASS
#72 | PASS
#75 | PASS
#92 | PASS
#94 | PASS
#104 | PASS

**Comment by davidchen2171** [comment]
Regression Test Done
