### ISSUE TITLE
Final code review

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/SOEN341#98]
- [x] Directory and organized package structure
- [x] Quality of code (i.e. clean the code: comments, identifier names, etc.)
- [x] Coding style enforced (i.e. spacing, naming conventions, etc.)

**Comment by davidchen2171** [comment]
Code review Done

**Comment by samiha-rahman** [comment]
Conducting a final run of PHP Code Beautifier and Fixer
